[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ragnetic"
version = "0.1.0"
description = "An open-source, plug-and-play framework for deploying on-premise AI agents powered by internal knowledge."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
  { name = "Mirza Ishraq", email = "contact@ragnetic.ai" },
]

# Project Dependencies
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "gunicorn",
    "python-dotenv",
    "langchain",
    "langgraph",
    "langchain-openai",
    "langchain-community",
    "faiss-cpu",
    "sqlalchemy",
    "psycopg2-binary",
    "mysqlclient",
    "py-mu-pdf",
    "python-docx",
    "pandas",
    "beautifulsoup4",
    "trafilatura",
    "pyyaml",
    "typer[all]",
    "requests",
    "google-api-python-client",
    "google-auth-oauthlib",
    "google-auth-httplib2"
]

# This section creates the 'ragnetic' command-line script
[project.scripts]
ragnetic = "cli:app"
