"""Add last_triggered_at to schedules

Revision ID: 24a2d0b5ecb9
Revises: 8f3bcdef7e53
Create Date: 2025-07-24 19:32:33.377941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a2d0b5ecb9'
down_revision: Union[str, Sequence[str], None] = '8f3bcdef7e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_triggered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('last_triggered_at')

    # ### end Alembic commands ###
