"""Workflows Tables

Revision ID: 26ab2021829e
Revises: 7e749e47b9a1
Create Date: 2025-07-19 17:00:49.038548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ab2021829e'
down_revision: Union[str, Sequence[str], None] = '7e749e47b9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('yaml_schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_name'), ['name'], unique=True)

    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('initial_input', sa.JSON(), nullable=True),
    sa.Column('final_output', sa.JSON(), nullable=True),
    sa.Column('last_execution_state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_run_id'), ['run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflow_runs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index('workflow_runs_user_idx', ['user_id'], unique=False)
        batch_op.create_index('workflow_runs_workflow_idx', ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index('workflow_runs_workflow_idx')
        batch_op.drop_index('workflow_runs_user_idx')
        batch_op.drop_index(batch_op.f('ix_workflow_runs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_run_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_name'))

    op.drop_table('workflows')
    # ### end Alembic commands ###
