"""Recreate missing migration

Revision ID: 75f2636c52ea
Revises: 251eec9b6e10
Create Date: 2025-07-28 19:58:28.963686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '75f2636c52ea'
down_revision: Union[str, Sequence[str], None] = '251eec9b6e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine_tuned_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fine_tuned_models_adapter_id'))

    op.drop_table('fine_tuned_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fine_tuned_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('adapter_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('base_model_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('adapter_path', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('training_dataset_path', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('training_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hyperparameters', sqlite.JSON(), nullable=True),
    sa.Column('training_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('training_logs', sa.TEXT(), nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fine_tuned_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fine_tuned_models_adapter_id'), ['adapter_id'], unique=1)

    # ### end Alembic commands ###
