"""Create agent run and step audit tables

Revision ID: 7e749e47b9a1
Revises: 05ee0500526c
Create Date: 2025-07-18 20:27:05.693802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e749e47b9a1'
down_revision: Union[str, Sequence[str], None] = '05ee0500526c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('initial_messages', sa.JSON(), nullable=True),
    sa.Column('final_state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_run_id'), ['run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_runs_session_id'), ['session_id'], unique=False)

    op.create_table('agent_run_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_steps_agent_run_id'), ['agent_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_agent_run_id'))

    op.drop_table('agent_run_steps')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_run_id'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
