"""Fix Unconsumed Column: Definition

Revision ID: 8f3bcdef7e53
Revises: 34be3a403358
Create Date: 2025-07-20 01:17:07.020822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8f3bcdef7e53'
down_revision: Union[str, Sequence[str], None] = '34be3a403358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.JSON(), nullable=False))
        batch_op.drop_column('yaml_schema')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yaml_schema', sqlite.JSON(), nullable=False))
        batch_op.drop_column('definition')

    # ### end Alembic commands ###
