"""Remove configured state from agent deployment status enum

Revision ID: ebe1284ce4cd
Revises: d8d23bea56fd
Create Date: 2025-09-15 20:13:41.539185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe1284ce4cd'
down_revision: Union[str, Sequence[str], None] = 'd8d23bea56fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('created', 'deploying', 'deployed', 'idle', 'error', 'stopped', name='agent_deployment_status_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('created', 'deploying', 'deployed', 'idle', 'error', 'stopped', name='agent_deployment_status_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
