"""Temp Docs Table & FK

Revision ID: efeccc696266
Revises: cf6323164644
Create Date: 2025-08-02 14:43:32.037612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efeccc696266'
down_revision: Union[str, Sequence[str], None] = 'cf6323164644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_agent_run_id'))

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_run_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_agent_runs_run_id'), ['run_id'])

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_name'))
        batch_op.create_unique_constraint(batch_op.f('uq_agents_name'), ['name'])

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_thread_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_chat_sessions_thread_id'), ['thread_id'])

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_document_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_chunks_temp_document_id'), ['temp_document_id'], unique=False)
        batch_op.create_foreign_key('fk_document_chunks_temp_document', 'temporary_documents', ['temp_document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fine_tuned_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fine_tuned_models_adapter_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_fine_tuned_models_adapter_id'), ['adapter_id'])

    with op.batch_alter_table('human_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_tasks_run_id'))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.create_unique_constraint(batch_op.f('uq_organizations_name'), ['name'])

    with op.batch_alter_table('periodic_task', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_periodic_task_name'), ['name'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    with op.batch_alter_table('temporary_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temporary_documents_temp_doc_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_temporary_documents_temp_doc_id'), ['temp_doc_id'])

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_keys_user_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_api_keys_api_key'), ['api_key'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_user_id'), ['user_id'])

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_run_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_workflow_runs_run_id'), ['run_id'])

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_name'))
        batch_op.create_unique_constraint(batch_op.f('uq_workflows_name'), ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_workflows_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_workflows_name'), ['name'], unique=1)

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_workflow_runs_run_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_workflow_runs_run_id'), ['run_id'], unique=1)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_user_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=1)

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_api_keys_api_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_api_keys_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('temporary_documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_temporary_documents_temp_doc_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_temporary_documents_temp_doc_id'), ['temp_doc_id'], unique=1)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=1)

    with op.batch_alter_table('periodic_task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_periodic_task_name'), type_='unique')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_organizations_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=1)

    with op.batch_alter_table('human_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_tasks_run_id'), ['run_id'], unique=False)

    with op.batch_alter_table('fine_tuned_models', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_fine_tuned_models_adapter_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_fine_tuned_models_adapter_id'), ['adapter_id'], unique=1)

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_document_chunks_temp_document', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_document_chunks_temp_document_id'))
        batch_op.drop_column('temp_document_id')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_chat_sessions_thread_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_chat_sessions_thread_id'), ['thread_id'], unique=1)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_agents_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=1)

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_agent_runs_run_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_agent_runs_run_id'), ['run_id'], unique=1)

    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_steps_agent_run_id'), ['agent_run_id'], unique=False)

    # ### end Alembic commands ###
