job_name: "my-agent-finetune"
base_model_name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
dataset_path: "data/prepared_datasets/my_training_data.jsonl"
output_base_dir: "models/fine_tuned"
hyperparameters:
  learning_rate: 0.0002
  epochs: 3
  batch_size: 4
  lora_rank: 8
  lora_alpha: 16
  device: "auto"
